jeeper:
  config:
    reference-packages: javax.persistence,
      java.lang,java.time,
      com.idaoben.web.common.api.bean,
      io.swagger.annotations,
      org.springframework.web.bind.annotation,
      org.springframework.stereotype,
      javax.annotation,
      com.idaoben.web.common.api.bean
spring:
  common-web:
    messages:
      encoding: UTF-8
      basename: classpath:i18n/messages
    format:
      pattern:
        date-time: dd-MM-yyyy HH:mm:ss
    api-log:
      type: all

